source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'mysql2', '~> 0.2.6'
gem 'authlogic'
gem 'will_paginate'
gem 'paperclip'
gem 'validates_timeliness'
gem 'prawn'
gem 'meta_where'
gem 'meta_search'
gem 'paper_trail'
gem 'state_machine'
gem 'whenever', :require => false
gem 'bluecloth'
gem 'cornell_netid'
gem 'cornell_ldap', '>= 1.3.1'
gem 'validation_reflection'
gem 'formtastic'
gem 'cocoon'
gem 'declarative_authorization', '>= 0.5'
gem 'composite_primary_keys', '~> 3.1.9', :require => false # CPK only required for registration importer
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete'
group :test do
  gem 'test-unit'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'factory_girl', '= 1.3.2'
  gem 'factory_girl_rails'
  gem 'pickle'
  gem 'email_spec'
  gem 'launchy'
end

