source 'http://rubygems.org'

gem 'rails', '3.1.0.rc5'
gem 'mysql2', '~> 0.2'
gem 'json'
gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'
gem 'authlogic'
gem 'kaminari'
gem 'carrierwave'
gem 'validates_timeliness'
gem 'prawn'
gem 'prawn-fast-png'
gem 'squeel'
gem 'meta_search', '~> 1.1.0.pre2'
gem 'paper_trail'
gem 'state_machine'
gem 'whenever', :require => false
gem 'bluecloth'
gem 'cornell_netid'
gem 'cornell_ldap', '>= 1.3.1'
gem 'validation_reflection'
gem 'formtastic'
gem 'cocoon', '~> 1.0.10'
gem 'declarative_authorization', '>= 0.5'
gem 'composite_primary_keys', '~> 4.0.0.beta7', :require => false # Require on demand
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete'
gem 'escape_utils'
gem 'ancestry'
gem 'acts_as_list', '~> 0.1.3'
gem 'decent_exposure'
group :development, :test do
  gem 'rspec-rails', '~> 2.6.1'
end
group :test do
  gem 'thin'
  gem 'test-unit'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'spork'
  gem 'factory_girl', '~> 2.0.0', :require => false
  gem 'factory_girl_rails', '~> 1.1.0'
  gem 'pickle', '~> 0.4.8'
  gem 'email_spec'
  gem 'launchy'
end

