source 'http://rubygems.org'

gem 'rails', '~>3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql'
#gem 'acts_as_tree'
gem 'authlogic'
gem 'will_paginate'
gem 'aasm'
gem 'paperclip'
gem 'validates_timeliness'
gem 'prawn'
gem 'meta_where'
gem 'meta_search'
gem 'whenever'
gem 'bluecloth'
gem 'cornell_netid'
gem 'cornell_ldap', '>= 1.3.1'
gem 'validation_reflection'
gem 'formtastic'
gem 'declarative_authorization', '>= 0.5'
gem 'composite_primary_keys', :git => 'git://github.com/aepstein/composite_primary_keys.git'
gem 'jquery-rails'
gem 'rails3-jquery-autocomplete'
group :test do
  gem 'test-unit'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
  gem 'factory_girl'
  gem 'pickle'
  gem 'email_spec'
  gem 'launchy'
end

