development:
  session_secret: 64cced0d99dabeb84b2e596eca215243ca31df9d96984f74a80b3ae1359595e4f23bb9983ef9ad874a82f0f17274b5305c5ab395d4941e6ffeada96795fdc5a4
  default_contact:
    name: Office of the Assemblies
    email: assembly@cornell.edu
  expenses:
    general:
      mailbox:
        existing: 25
        new: 40
      copies: 0.03
      chalk: 8.0
    speaker:
      travel: 0.5
      lodging: 75.0
      meals: 30.0
    travel:
      travel: 0.063
      lodging: 15.0

test:
  session_secret: 64cced0d99dabeb84b2e596eca215243ca31df9d96984f74a80b3ae1359595e4f23bb9983ef9ad874a82f0f17274b5305c5ab395d4941e6ffeada96795fdc5a4
  default_contact:
    name: Office of the Assemblies
    email: assembly@cornell.edu
  expenses:
    general:
      mailbox:
        existing: 25
        new: 40
      copies: 0.03
      chalk: 8.0
    speaker:
      travel: 0.5
      lodging: 75.0
      meals: 30.0
    travel:
      travel: 0.063
      lodging: 15.0

production:
  session_secret: 64cced0d99dabeb84b2e596eca215243ca31df9d96984f74a80b3ae1359595e4f23bb9983ef9ad874a82f0f17274b5305c5ab395d4941e6ffeada96795fdc5a4
  default_contact:
    name: Office of the Assemblies
    email: assembly@cornell.edu
  expenses:
    general:
      mailbox:
        existing: 25
        new: 40
      copies: 0.03
      chalk: 8.0
    speaker:
      travel: 0.5
      lodging: 75.0
      meals: 30.0
    travel:
      travel: 0.063
      lodging: 15.0

